# Generated by Django 3.1.3 on 2020-12-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('queueApp', '0002_delete_addtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddWaitTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('tempo', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
