# Generated by Django 3.1.3 on 2020-12-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueApp', '0004_addwaittime_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addwaittime',
            name='endereco',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
