# Generated by Django 3.1.3 on 2020-12-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueApp', '0005_auto_20201201_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addwaittime',
            name='endereco',
            field=models.CharField(max_length=400),
        ),
    ]
